apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: returnPolicy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: returnPolicy
    spec:
      containers:
      - image: amela/return_policy
        name: returnPolicy
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-returnPolicy:5432/returnPolicy
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.20.118:31331 
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP
